export type LeistungsbereichTag =
  | "Baumarbeiten"
  | "Grünflächenpflege"
  | "Tiefbau"
  | "Gartenbau"
  | "Innenausbau"
  | "Sonstige Leistungen";

export interface Referenz {
  id: string;
  title: string;
  tags: LeistungsbereichTag[];
  subtag?: string;
  images: string[];
}

export const SUBTAGS: Partial<Record<LeistungsbereichTag, string[]>> = {
  Baumarbeiten: [
    "Kletterarbeiten & Kronenpflege",
    "Baumfällungen",
    "Wurzelstockentfernung mit Stuppenfräse",
    "Rodung & Entbuschung",
    "Obstbaumschnitt",
  ],
  Grünflächenpflege: [
    "Objektpflege & Heckenschnitte",
    "Pflanzungen",
  ],
  Tiefbau: [
    "Pflasterarbeiten aller Art",
    "Abwasser / Wasser / Strom",
    "Trockenlegung Keller",
  ],
  Gartenbau: [
    "Mauerbau",
    "Zaunbau",
    "Hochbeete",
    "Teichbau",
    "Carports u. Gartenhäuser",
    "Spielplätze",
  ],
  Innenausbau: [
    "Trockenbau",
    "Fliesenarbeiten",
    "Deckenarbeiten",
    "Fußböden",
  ],
};

const PH = (n: number) => Array.from({ length: n }, (_, i) => `/images/referenzen/placeholder.jpg`);

export const REFERENZEN: Referenz[] = [
  {
    id: "kletterarbeiten-kronenpflege",
    title: "Kletterarbeiten & Kronenpflege",
    tags: ["Baumarbeiten"],
    subtag: "Kletterarbeiten & Kronenpflege",
    images: [
      "/images/referenzen/Baumpflege 01/Kletterarbeiten und Kronenpflege.jpg",
      "/images/referenzen/Baumpflege 01/Kronenpflege .jpg",
      "/images/referenzen/Baumpflege 01/Kronenpflege.jpg",
    ],
  },
  {
    id: "baumfaellungen",
    title: "Baumfällungen",
    tags: ["Baumarbeiten"],
    subtag: "Baumfällungen",
    images: [
      "/images/referenzen/Baumpflege 01/Baumfällungen.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 1.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällung 3.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 4.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 5.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen (1).jpg",
    ],
  },
  {
    id: "wurzelstockentfernung",
    title: "Wurzelstockentfernung mit Stuppenfräse",
    tags: ["Baumarbeiten"],
    subtag: "Wurzelstockentfernung mit Stuppenfräse",
    images: [
      "/images/referenzen/Baumpflege 01/Wurzelstockentfernung mit Stuppenfräse.jpg",
    ],
  },
  {
    id: "rodung-entbuschung",
    title: "Rodung & Entbuschung",
    tags: ["Baumarbeiten"],
    subtag: "Rodung & Entbuschung",
    images: [
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Forstmulcher Raupe.jpg",
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Forstraupe.jpg",
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Traktor und Häcksler.jpg",
    ],
  },
  {
    id: "obstbaumschnitt",
    title: "Obstbaumschnitt",
    tags: ["Baumarbeiten"],
    subtag: "Obstbaumschnitt",
    images: [
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt 1 Meura.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt 2 Meura.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Altbaumschnitt.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Jungbaum 1.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Jungbaum 2.jpg",
    ],
  },
  {
    id: "pflasterarbeiten-rudolstadt",
    title: "Pflasterarbeiten Rudolstadt Teichel",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/Parkplatzbau.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/AGUQ2345.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/FKFY5401.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/GOKW9468.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3754.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3820.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3952.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4120.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4205.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4333.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4351.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4594.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4595.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4612.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4654.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4674.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4743.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4804.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4804 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4937.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4943.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/JBGX6194.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/JJPZ5942.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/LYJW9651.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/MQRF9960.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/TASF2009.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/YIPQ1615.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/YJEA3048.jpg",
    ],
  },
  {
    id: "pflasterarbeiten-koenitz",
    title: "Pflasterarbeiten Könitz",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 51 04.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 51 17.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 57 54.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.05.25, 16 46 56.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.05.25, 16 47 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.09.25, 17 36 50.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 22.08.25, 11 49 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 26.08.25, 16 27 36.jpg",
    ],
  },
  {
    id: "drainage-pflaster-poessneck",
    title: "Drainage Pflaster Pößneck",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/Hauptbild Leistungsbereich Querformat 03.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/ACAN5562.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4804.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4821.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4963.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5069.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5172.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5174.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/PEXK9404.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/SXEV0035.jpg",
    ],
  },
  {
    id: "feuerwehrzufahrt-poessneck",
    title: "Feuerwehrzufahrt Pößneck",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 04.03.26, 14 54 52.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 04.03.26, 14 54 52 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 05.05.25, 13 13 24.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 08.05.25, 12 17 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 11 39 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 15 04 14.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 17 46 53.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 21.05.25, 11 39 58.jpg",
    ],
  },
  {
    id: "rasengitter-beton",
    title: "Rasengitter Beton",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 08 44 41.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 08 44 41 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 13 24 10.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 27.04.23, 13 28 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 27.05.23, 08 32 18.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 03.11.25, 15 16 07.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 04.03.26, 14 56 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 05.11.25, 17 05 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 11.11.25, 16 18 42.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 12.11.25, 16 27 06.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 12.11.25, 16 27 42.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 17.11.25, 09 41 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 18.11.25, 13 59 32.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 22.05.25, 11 18 02.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 25.11.25, 15 50 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 26.11.25, 11 14 42.jpg",
    ],
  },
  {
    id: "gasstation-schmiedefeld",
    title: "Beton Pflaster Gasstation Schmiedefeld",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 04.03.26, 15 38 44.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 06.07.23, 11 09 30.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 07.07.23, 11 07 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 07.07.23, 11 08 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 29.06.23, 15 19 03.jpg",
    ],
  },
  {
    id: "granitpflaster",
    title: "Granitpflaster Katzensteig",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 24.03.26, 11 08 23.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 27.03.26, 17 10 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 10 46 24.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 10 51 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 19 39 10.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 19 39 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 02.04.26, 16 12 04.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 11 22 14.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 11 22 22.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 16 54 15.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 17 05 58.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 08.04.26, 13 05 45.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 09.04.26, 18 49 48.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 15.04.26, 08 54 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 15.04.26, 08 55 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 17.04.26, 11 16 07.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 20.04.26, 18 02 31.jpg",
    ],
  },
  {
    id: "abwasser-wasser-strom",
    title: "Abwasser / Wasser / Strom",
    tags: ["Tiefbau"],
    subtag: "Abwasser / Wasser / Strom",
    images: [
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/CCKQ1294.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/EGTN5749.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/GHCG6484.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IBMT9399.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1471.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1528.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1594.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1725.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_2061.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_2414.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_4114.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_5766.jpg",
    ],
  },
  {
    id: "hochbeet-holz",
    title: "Holzhochbeet",
    tags: ["Gartenbau"],
    subtag: "Hochbeete",
    images: [
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 04.03.26, 15 25 59.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 08.08.24, 10 06 58.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 09.04.24, 08 51 27.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 10.04.24, 14 59 27.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 12.03.24, 07 44 49.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 26.03.24, 17 44 59.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 29.07.24, 13 35 53.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet Holz/Foto 29.07.24, 13 36 03.jpg",
    ],
  },
  {
    id: "hochbeet-stein",
    title: "Steinhochbeet",
    tags: ["Gartenbau"],
    subtag: "Hochbeete",
    images: [
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet 2 Stein/Foto 02.05.23, 09 20 21.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet 2 Stein/Foto 04.04.23, 13 41 22.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet 2 Stein/Foto 05.05.23, 09 34 50.jpg",
      "/images/referenzen/Gartenbau 04/Hochbeete/Hochbeet 2 Stein/Foto 12.04.23, 14 16 13.jpg",
    ],
  },
  {
    id: "trockenbau",
    title: "Trockenbau",
    tags: ["Innenausbau"],
    subtag: "Trockenbau",
    images: [
      "/images/referenzen/Innenausbau 05/Trockenbau/Foto 01.01.23, 15 04 59.jpg",
      "/images/referenzen/Innenausbau 05/Trockenbau/Foto 01.02.23, 16 24 43.jpg",
      "/images/referenzen/Innenausbau 05/Trockenbau/Foto 19.06.24, 14 23 42.jpg",
      "/images/referenzen/Innenausbau 05/Trockenbau/Foto 25.01.23, 16 57 40 (1).jpg",
    ],
  },
  {
    id: "fliesenarbeiten",
    title: "Fliesenarbeiten",
    tags: ["Innenausbau"],
    subtag: "Fliesenarbeiten",
    images: [
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 01.06.23, 07 20 28.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 09.01.24, 14 29 09.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 11.06.24, 13 26 20.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 15.05.23, 15 16 47.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 18.05.25, 10 05 52.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 18.05.25, 10 06 21.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 26.10.23, 07 38 09.jpg",
      "/images/referenzen/Innenausbau 05/Fliesen-Arbeiten/Foto 31.05.23, 16 40 29.jpg",
    ],
  },
  {
    id: "deckenarbeiten",
    title: "Deckenarbeiten",
    tags: ["Innenausbau"],
    subtag: "Deckenarbeiten",
    images: [
      "/images/referenzen/Innenausbau 05/Deckenarbeiten/Foto 02.08.23, 15 12 18.jpg",
      "/images/referenzen/Innenausbau 05/Deckenarbeiten/Foto 05.12.23, 19 39 37.jpg",
      "/images/referenzen/Innenausbau 05/Deckenarbeiten/Foto 18.05.25, 10 04 31.jpg",
    ],
  },
  {
    id: "fussboeden",
    title: "Fußböden",
    tags: ["Innenausbau"],
    subtag: "Fußböden",
    images: [
      "/images/referenzen/Innenausbau 05/Fußbodenarbeiten/Foto 23.01.23, 11 27 17.jpg",
    ],
  },
  {
    id: "kammmolchgewaesser",
    title: "Kammmolchgewässer Weichwitz",
    tags: ["Gartenbau"],
    subtag: "Teichbau",
    images: [
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 01.09.23, 14 32 40.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 04.03.26, 15 46 39.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 04.09.23, 18 31 22.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 04.09.23, 18 31 23 (1).jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 04.09.23, 18 31 23.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 06.09.23, 15 39 50.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 06.09.23, 15 40 12.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 07.09.23, 15 01 56.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 25.08.23, 14 05 58.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 26.08.23, 18 13 38.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Kammmolchgewässer/Foto 27.09.23, 17 12 02.jpg",
    ],
  },
  {
    id: "koenitz-aussenanlage",
    title: "Objektpflege & Heckenschnitte",
    tags: ["Grünflächenpflege"],
    subtag: "Objektpflege & Heckenschnitte",
    images: [
      "/images/referenzen/Grünflächenpflege 02/Objektpflege.jpeg",
      "/images/referenzen/Grünflächenpflege 02/Heckenschnitte.jpg",
      "/images/referenzen/Grünflächenpflege 02/Objektpflege Heckenschnitte.jpg",
    ],
  },
  {
    id: "landhausmauer-1",
    title: "Landhausmauer",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: [
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 04.03.26, 15 51 27 (1).jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 04.03.26, 15 51 27.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 09.05.23, 12 35 42.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 12.05.23, 10 28 27.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 12.05.23, 17 54 33.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 12.06.23, 17 30 23 (1).jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 12.06.23, 17 30 23.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 14.06.23, 18 59 01.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 14.06.23, 18 59 02 (1).jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 14.06.23, 18 59 02.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 15.06.23, 20 25 00.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 16.06.23, 19 49 14.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 17.07.23, 15 54 41.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 17.07.23, 15 54 42.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 1/Foto 30.05.23, 14 38 09.jpg",
    ],
  },
  {
    id: "landhausmauer-2",
    title: "Landhausmauer 2",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: [
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 2/Foto 15.05.25, 16 47 16.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 2/Foto 15.09.25, 13 36 46.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 2/Foto 16.08.25, 14 19 54.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 2/Foto 26.08.25, 16 27 05.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Landhausmauer 2/Foto 26.08.25, 16 27 36.jpg",
    ],
  },
  {
    id: "lego-stein-mauer",
    title: "Lego-Stein-Mauer",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: [
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 07.06.23, 13 59 56.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 09.06.23, 10 49 22.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 13.06.23, 13 42 40.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 19.06.23, 10 13 51.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 19.06.23, 16 03 29.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/Legosteinmauer/Foto 21.06.23, 18 06 07.jpg",
    ],
  },
  {
    id: "l-steinmauer",
    title: "L-Steinmauer",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: [
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 01.07.24, 15 37 45.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 05.07.24, 15 38 46.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 12.06.24, 17 21 54.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 13.06.24, 12 57 22.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 13.06.24, 17 04 33.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 20.03.24, 18 47 28.jpg",
      "/images/referenzen/Gartenbau 04/Mauer-Bau/L-Steinmauer/Foto 28.06.24, 15 05 22.jpg",
    ],
  },
  {
    id: "pflanzung",
    title: "Pflanzungen",
    tags: ["Grünflächenpflege"],
    subtag: "Pflanzungen",
    images: [
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Baumpflanzung 1.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Baumpflanzung 2.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/CNIA1516.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Foto 12.12.25, 11 45 58.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/QQJG0859.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Strauch-Pflanzung 3.jpg",
    ],
  },
  {
    id: "teich-seisla",
    title: "Natur-Teich Seisla",
    tags: ["Gartenbau"],
    subtag: "Teichbau",
    images: [
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 04.03.26, 15 34 09 (1).jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 04.03.26, 15 34 09.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 11.07.23, 15 09 44.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 12.07.23, 13 39 29.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 12.07.23, 22 55 51 (1).jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 13.07.23, 10 10 41.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 13.07.23, 17 36 13.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 13.07.23, 17 56 27.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 14.07.23, 06 12 32.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 14.07.23, 16 37 25.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 14.07.23, 16 38 38.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 14.07.23, 16 39 30.jpg",
      "/images/referenzen/Gartenbau 04/Teichbau/Natur Teich Seisla/Foto 14.07.23, 16 39 48.jpg",
    ],
  },
  {
    id: "holz-senkrecht-zaun",
    title: "Holz-Senkrecht-Zaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Senkrechtzaun Schmiedefeld/DNYI2101.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Senkrechtzaun Schmiedefeld/GNCF2424.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Senkrechtzaun Schmiedefeld/IMG_1078.jpg",
    ],
  },
  {
    id: "holz-sichtschutzzaun",
    title: "Holz-Sichtschutzzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Sichtschutzzaun Schmiedefeld/KJGE2746.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Sichtschutzzaun Schmiedefeld/MEGF5536.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Sichtschutzzaun Schmiedefeld/OWGW5644.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Holz-Sichtschutzzaun Schmiedefeld/SXNO7127.jpg",
    ],
  },
  {
    id: "kunststoff-sichtschutzzaun",
    title: "Kunststoff-Sichtschutzzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 01.07.26, 16 54 55 (1) (1).jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 01.07.26, 16 54 55 (1).jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 01.07.26, 16 54 55.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 18.06.26, 11 47 07.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 23.06.26, 19 12 29.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 23.06.26, 19 12 32.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Sichtschutzzaun Kunststoff/Foto 25.06.26, 11 37 30.jpg",
    ],
  },
  {
    id: "maschendrahtzaun",
    title: "Maschendrahtzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/CENW7493.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_1163~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_20220610_151817.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_20220711_105716.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_20220711_105722.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_20220711_105737.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/IMG_20220711_105745.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaun Schmiedefeld (Maschendraht)/QZVJ5582.jpg",
    ],
  },
  {
    id: "wildzaun",
    title: "Wildzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Eyba Wildzaun/IMG_0261.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Eyba Wildzaun/IMG_0263.jpg",
    ],
  },
  {
    id: "stabmattenzaun",
    title: "Stabmattenzaun Allgemein",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 01.07.26, 23 41 48.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 08.12.25, 15 50 27 (1).jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 08.12.25, 15 50 27.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 08.12.25, 15 50 28.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 20.03.26, 14 50 08 (1).jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 20.03.26, 14 50 08.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Stabmattenzaun Allgemein/Foto 26.03.26, 14 54 00.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6165~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6166~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6167~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6168~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6169~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6170~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6171~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6173~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6175~photo.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Unterwellenborn Stabmattenzaun/IMG_6734~photo.jpg",
    ],
  },
  {
    id: "staketenzaun",
    title: "Staketenzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: [
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Kamsdorf Staketenzaun/LWKE0542.jpg",
      "/images/referenzen/Gartenbau 04/Zaunbau Neu/Zaunbau Kamsdorf Staketenzaun/RHVK3447.jpg",
    ],
  },
  {
    id: "carports-gartenhauser",
    title: "Carports u. Gartenhäuser",
    tags: ["Gartenbau"],
    subtag: "Carports u. Gartenhäuser",
    images: [
      "/images/referenzen/Gartenbau 04/Carports Stallungen Gartenhäuser/Carports, Stallbau.jpg",
      "/images/referenzen/Gartenbau 04/Carports Stallungen Gartenhäuser/Holzbau.jpg",
      "/images/referenzen/Gartenbau 04/Carports Stallungen Gartenhäuser/IMG_7812.jpg",
    ],
  },
  {
    id: "spielplatz-schwarza",
    title: "Spielplatz Rudolstadt Schwarza",
    tags: ["Gartenbau"],
    subtag: "Spielplätze",
    images: [
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 19.05.26, 12 25 15.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 19.05.26, 15 45 57.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 19.05.26, 15 46 00.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 20.05.26, 15 13 10.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 20.05.26, 15 13 14.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 22.05.26, 10 58 13.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 23.05.26, 11 18 43.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 27.05.26, 15 47 04.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 27.05.26, 15 47 57.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 27.05.26, 15 48 10.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 28.05.26, 10 31 40.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 28.05.26, 10 32 17.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 28.05.26, 10 32 22.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 28.05.26, 10 32 40.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 30.05.26, 20 05 41.jpg",
      "/images/referenzen/Gartenbau 04/Spielplatzbau/Spielplatzbau Rudolstadt Schwarza/Foto 30.05.26, 20 06 57.jpg",
    ],
  },
  {
    id: "trockenlegung-keller",
    title: "Trockenlegung Keller Pößneck",
    tags: ["Tiefbau"],
    subtag: "Trockenlegung Keller",
    images: [
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 19.07.23, 15 43 35.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 19.07.23, 16 30 39.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 09 02 07.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 09 48 52.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 11 16 58.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 13 06 49.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 17 49 46.jpg",
    ],
  },
];

export const ALL_TAGS: LeistungsbereichTag[] = [
  "Baumarbeiten",
  "Grünflächenpflege",
  "Tiefbau",
  "Gartenbau",
  "Innenausbau",
];
