export type LeistungsbereichTag =
  | "Baumarbeiten"
  | "Grünflächenpflege"
  | "Tiefbau"
  | "Gartenbau"
  | "Innenausbau"
  | "Sonstige Leistungen";

export interface Referenz {
  id: string;
  title: string;
  tags: LeistungsbereichTag[];
  subtag?: string;
  images: string[];
}

export const SUBTAGS: Partial<Record<LeistungsbereichTag, string[]>> = {
  Baumarbeiten: [
    "Kletterarbeiten & Kronenpflege",
    "Baumfällungen",
    "Wurzelstockentfernung mit Stuppenfräse",
    "Rodung & Entbuschung",
    "Obstbaumschnitt",
  ],
  Grünflächenpflege: [
    "Objektpflege & Heckenschnitte",
    "Pflanzungen",
  ],
  Tiefbau: [
    "Pflasterarbeiten aller Art",
    "Abwasser / Wasser / Strom",
    "Trockenlegung Keller",
  ],
  Gartenbau: [
    "Mauerbau",
    "Zaunbau",
    "Hochbeete",
    "Teichbau",
    "Carports u. Gartenhäuser",
    "Spielplätze",
  ],
};

const PH = (n: number) => Array.from({ length: n }, (_, i) => `/images/referenzen/placeholder.jpg`);

export const REFERENZEN: Referenz[] = [
  {
    id: "kletterarbeiten-kronenpflege",
    title: "Kletterarbeiten & Kronenpflege",
    tags: ["Baumarbeiten"],
    subtag: "Kletterarbeiten & Kronenpflege",
    images: [
      "/images/referenzen/Baumpflege 01/Kletterarbeiten und Kronenpflege.jpg",
      "/images/referenzen/Baumpflege 01/Kronenpflege .jpg",
      "/images/referenzen/Baumpflege 01/Kronenpflege.jpg",
    ],
  },
  {
    id: "baumfaellungen",
    title: "Baumfällungen",
    tags: ["Baumarbeiten"],
    subtag: "Baumfällungen",
    images: [
      "/images/referenzen/Baumpflege 01/Baumfällungen.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 1.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällung 3.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 4.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen 5.jpg",
      "/images/referenzen/Baumpflege 01/Baumfällungen (1).jpg",
    ],
  },
  {
    id: "wurzelstockentfernung",
    title: "Wurzelstockentfernung mit Stuppenfräse",
    tags: ["Baumarbeiten"],
    subtag: "Wurzelstockentfernung mit Stuppenfräse",
    images: [
      "/images/referenzen/Baumpflege 01/Wurzelstockentfernung mit Stuppenfräse.jpg",
    ],
  },
  {
    id: "rodung-entbuschung",
    title: "Rodung & Entbuschung",
    tags: ["Baumarbeiten"],
    subtag: "Rodung & Entbuschung",
    images: [
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Forstmulcher Raupe.jpg",
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Forstraupe.jpg",
      "/images/referenzen/Baumpflege 01/Entbuschung Rodung mit Traktor und Häcksler.jpg",
    ],
  },
  {
    id: "obstbaumschnitt",
    title: "Obstbaumschnitt",
    tags: ["Baumarbeiten"],
    subtag: "Obstbaumschnitt",
    images: [
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt 1 Meura.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt 2 Meura.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Altbaumschnitt.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Jungbaum 1.jpg",
      "/images/referenzen/Baumpflege 01/Obstbaumschnitt/Obstbaumschnitt Jungbaum 2.jpg",
    ],
  },
  {
    id: "pflasterarbeiten-rudolstadt",
    title: "Pflasterarbeiten Rudolstadt Teichel",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/Parkplatzbau.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/AGUQ2345.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/FKFY5401.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/GOKW9468.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3754.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3820.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_3952.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4120.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4205.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4333.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4351.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4594.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4595.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4612.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4654.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4674.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4743.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4804.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4804 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4937.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/IMG_4943.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/JBGX6194.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/JJPZ5942.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/LYJW9651.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/MQRF9960.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/TASF2009.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/YIPQ1615.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Rudolstadt Teichel 1/YJEA3048.jpg",
    ],
  },
  {
    id: "pflasterarbeiten-koenitz",
    title: "Pflasterarbeiten Könitz",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 51 04.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 51 17.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 03.09.25, 15 57 54.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.05.25, 16 46 56.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.05.25, 16 47 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 15.09.25, 17 36 50.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 22.08.25, 11 49 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflasterarbeiten Könitz/Foto 26.08.25, 16 27 36.jpg",
    ],
  },
  {
    id: "drainage-pflaster-poessneck",
    title: "Drainage Pflaster Pößneck",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/Hauptbild Leistungsbereich Querformat 03.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/ACAN5562.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4804.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4821.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_4963.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5069.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5172.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/IMG_5174.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/PEXK9404.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Drainagepflaster Pößneck 1/SXEV0035.jpg",
    ],
  },
  {
    id: "feuerwehrzufahrt-poessneck",
    title: "Feuerwehrzufahrt Pößneck",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 04.03.26, 14 54 52.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 04.03.26, 14 54 52 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 05.05.25, 13 13 24.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 08.05.25, 12 17 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 11 39 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 15 04 14.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 14.05.25, 17 46 53.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Baustelle Pößneck Feuerwehrzufahrt/Foto 21.05.25, 11 39 58.jpg",
    ],
  },
  {
    id: "rasengitter-beton",
    title: "Rasengitter Beton",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 08 44 41.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 08 44 41 (1).jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 25.05.23, 13 24 10.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 27.04.23, 13 28 16.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Rasengitter Beton/Foto 27.05.23, 08 32 18.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 03.11.25, 15 16 07.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 04.03.26, 14 56 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 05.11.25, 17 05 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 11.11.25, 16 18 42.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 12.11.25, 16 27 06.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 12.11.25, 16 27 42.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 17.11.25, 09 41 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 18.11.25, 13 59 32.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 22.05.25, 11 18 02.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 25.11.25, 15 50 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Kunststoff Rasengitter Baustelle Pößneck Parkplatz/Foto 26.11.25, 11 14 42.jpg",
    ],
  },
  {
    id: "gasstation-schmiedefeld",
    title: "Beton Pflaster Gasstation Schmiedefeld",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 04.03.26, 15 38 44.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 06.07.23, 11 09 30.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 07.07.23, 11 07 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 07.07.23, 11 08 38.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Pflaster Vorwerk Gasstation/Foto 29.06.23, 15 19 03.jpg",
    ],
  },
  {
    id: "granitpflaster",
    title: "Granitpflaster Katzensteig",
    tags: ["Tiefbau"],
    subtag: "Pflasterarbeiten aller Art",
    images: [
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 24.03.26, 11 08 23.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 27.03.26, 17 10 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 10 46 24.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 10 51 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 19 39 10.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 01.04.26, 19 39 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 02.04.26, 16 12 04.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 11 22 14.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 11 22 22.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 16 54 15.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 07.04.26, 17 05 58.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 08.04.26, 13 05 45.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 09.04.26, 18 49 48.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 15.04.26, 08 54 46.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 15.04.26, 08 55 01.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 17.04.26, 11 16 07.jpg",
      "/images/referenzen/Tiefbau 03/Pflasterarbeiten/Granitpflaster/Foto 20.04.26, 18 02 31.jpg",
    ],
  },
  {
    id: "abwasser-wasser-strom",
    title: "Abwasser / Wasser / Strom",
    tags: ["Tiefbau"],
    subtag: "Abwasser / Wasser / Strom",
    images: [
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/CCKQ1294.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/EGTN5749.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/GHCG6484.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IBMT9399.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1471.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1528.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1594.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_1725.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_2061.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_2414.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_4114.jpg",
      "/images/referenzen/Tiefbau 03/Abwasser  Wasser  Strom/IMG_5766.jpg",
    ],
  },
  {
    id: "hochbeet-holz",
    title: "Holzhochbeet",
    tags: ["Gartenbau"],
    subtag: "Hochbeete",
    images: PH(6),
  },
  {
    id: "hochbeet-stein",
    title: "Steinhochbeet",
    tags: ["Gartenbau"],
    subtag: "Hochbeete",
    images: PH(4),
  },
  {
    id: "innenausbau",
    title: "Innenausbau",
    tags: ["Innenausbau"],
    images: PH(6),
  },
  {
    id: "kammmolchgewaesser",
    title: "Kammmolchgewässer Weichwitz",
    tags: ["Gartenbau"],
    subtag: "Teichbau",
    images: PH(6),
  },
  {
    id: "koenitz-aussenanlage",
    title: "Objektpflege & Heckenschnitte",
    tags: ["Grünflächenpflege"],
    subtag: "Objektpflege & Heckenschnitte",
    images: [
      "/images/referenzen/Grünflächenpflege 02/Objektpflege.jpeg",
      "/images/referenzen/Grünflächenpflege 02/Heckenschnitte.jpg",
      "/images/referenzen/Grünflächenpflege 02/Objektpflege Heckenschnitte.jpg",
    ],
  },
  {
    id: "landhausmauer-1",
    title: "Landhausmauer 1",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: PH(6),
  },
  {
    id: "landhausmauer-2",
    title: "Landhausmauer 2",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: PH(6),
  },
  {
    id: "lego-stein-mauer",
    title: "Lego-Stein-Mauer",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: PH(6),
  },
  {
    id: "l-steinmauer",
    title: "L-Steinmauer",
    tags: ["Gartenbau"],
    subtag: "Mauerbau",
    images: PH(6),
  },
  {
    id: "pflanzung",
    title: "Pflanzungen",
    tags: ["Grünflächenpflege"],
    subtag: "Pflanzungen",
    images: [
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Baumpflanzung 1.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Baumpflanzung 2.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/CNIA1516.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Foto 12.12.25, 11 45 58.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/QQJG0859.jpg",
      "/images/referenzen/Grünflächenpflege 02/Pflanzung/Strauch-Pflanzung 3.jpg",
    ],
  },
  {
    id: "teich-seisla",
    title: "Natur-Teich Seisla",
    tags: ["Gartenbau"],
    subtag: "Teichbau",
    images: PH(6),
  },
  {
    id: "holz-senkrecht-zaun",
    title: "Holz-Senkrecht-Zaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "holz-sichtschutzzaun",
    title: "Holz-Sichtschutzzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "kunststoff-sichtschutzzaun",
    title: "Kunststoff-Sichtschutzzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "maschendrahtzaun",
    title: "Maschendrahtzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "wildzaun",
    title: "Wildzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "stabmattenzaun",
    title: "Stabmattenzaun Allgemein",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "staketenzaun",
    title: "Staketenzaun",
    tags: ["Gartenbau"],
    subtag: "Zaunbau",
    images: PH(6),
  },
  {
    id: "carports-gartenhauser",
    title: "Carports u. Gartenhäuser",
    tags: ["Gartenbau"],
    subtag: "Carports u. Gartenhäuser",
    images: PH(6),
  },
  {
    id: "spielplatz-schwarza",
    title: "Spielplatz Rudolstadt Schwarza",
    tags: ["Gartenbau"],
    subtag: "Spielplätze",
    images: PH(6),
  },
  {
    id: "trockenlegung-keller",
    title: "Trockenlegung Keller Pößneck",
    tags: ["Tiefbau"],
    subtag: "Trockenlegung Keller",
    images: [
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 19.07.23, 15 43 35.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 19.07.23, 16 30 39.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 09 02 07.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 09 48 52.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 11 16 58.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 13 06 49.jpg",
      "/images/referenzen/Tiefbau 03/Trockenlegung Keller Pößneck/Foto 27.07.23, 17 49 46.jpg",
    ],
  },
];

export const ALL_TAGS: LeistungsbereichTag[] = [
  "Baumarbeiten",
  "Grünflächenpflege",
  "Tiefbau",
  "Gartenbau",
  "Innenausbau",
];
